[package]
name = "dlg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.5"
console = "0.15.0"
dialoguer = "0.10.1"
